### ISSUE TITLE
Name suggestion

### ISSUE THREAD

**Issue by aL3xa** [jeroen/resttesttest#1]
Please reconsider appending `test` to app's title. The current one is not addressing the application's purpose... enough.

**Comment by jeroen** [comment]
Thank you for your always valuable suggestions. Your comments have been taken into consideration.

(ps: resttest.com was taken already :-)

**Comment by aL3xa** [comment]
Jeez, I completely forgot about my _momentary lapse of reason_! =)

**Comment by jeroen** [comment]
ps did you know that you can use github to host websites? resttesttest.com is simply pointing to the gh-pages branch of this repo... updating the website is a simple git push... pretty cool stuff

**Comment by aL3xa** [comment]
Sure, and there's Jekyl, yet another awesome thing form Ruby/Rails toolset. That's exactly how @daroczig and I managed pages for `rapport`. It's only that @daroczig bought a sleek new domain name, inside it's just GH hosting. =)
