### ISSUE TITLE
CORS not working

### ISSUE THREAD

**Issue by fsilkswan** [jeroen/resttesttest#6]
Using https://resttesttest.com it is not possible to retrieve data with a GET request from my REST API. My server is using Silex with CorsServiceProvider (JDesrosiers\Silex\Provider\CorsServiceProvider).
Using http://test-cors.org/ works.

Is it because resttesttest.com is using HTTP**S**?

**Comment by jeroen** [comment]
Only your **server** can enable cors by setting the correct cross origin headers. I think you can define in your cors headers whether or not access from http domains is allowed.

Note that the site also runs on https: https://resttesttest.com/
